# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: mpv.net
PackageVersion: 7.1.2.0
InstallerType: inno
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.10
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/mpvnet-player/mpv.net/releases/download/v7.1.2.0/mpv.net-v7.1.2.0-setup-x64.exe
  InstallerSha256: D9AD12A9BC007576506EB632BEF0D79389EB0C25D113AB4E22DCB75E386B81D7
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/mpvnet-player/mpv.net/releases/download/v7.1.2.0/mpv.net-v7.1.2.0-setup-x64.exe
  InstallerSha256: D9AD12A9BC007576506EB632BEF0D79389EB0C25D113AB4E22DCB75E386B81D7
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2026-01-09
